name: Documentation

on:
  push:
    branches: [main]
    paths:
      - docs/**
      - docs.yml
      - .github/workflows/docs.yml
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    uses: Laidwin/kiln/.github/workflows/pages.yml@v1
